# Experiment
experiment_name: dcgan-mnist
unique_experiment_name: dcgan-mnist_another-normal

# Data
dataloader: MNISTDataloader

# Model
channels: 1
image_size: 32
latent_size: 64

# Training
batch_size: 64
train_steps: 1000000
warm_start: False
gen_lr: 0.0001
gen_betas:
  - 0.5
  - 0.999
disc_lr: 0.0001
disc_betas:
  - 0.5
  - 0.999
