# Experiment
experiment_name: progan-mnist
unique_experiment_name: progan-mnist_overcast-amplifier

# Data
dataloader: MNISTDataloader

# Model
channels: 1
image_size: 32
latent_size: 64

# Training
batch_size: 16
train_steps: 50000
eval_rate: 6666
warm_start: True
gen_lr: 0.0002
gen_betas:
  - 0.5
  - 0.999
disc_lr: 0.0002
disc_betas:
  - 0.5
  - 0.999

