# Experiment
experiment_name: progan-spotify
unique_experiment_name: progan-spotify_boxy-bongo

# Data
dataloader: SpotifyDataloader
meta_data_path: data/album_data_frame.json

# Model
channels: 3
image_size: 64
latent_size: 512

# Training
batch_size:
  4: 16
  8: 16
  16: 16
  32: 16
  64: 16
fade_in_imgs: 800000
burn_in_imgs: 800000
n_evals: 10
warm_start: False
gen_lr: 0.001
gen_betas:
  - 0.0
  - 0.99
disc_lr: 0.001
disc_betas:
  - 0.0
  - 0.99
test_meta_data_path: data/test_data_meta.json
