# Experiment
experiment_name: stylegan-mnist
unique_experiment_name: stylegan-mnist_late-kitchen

# Data
dataloader: MNISTDataloader

# Model
channels: 1
image_size: 32
latent_size: 64
n_mapping: 4

# Training
batch_size: 16
train_steps: 50000
eval_rate: 6666
warm_start: True
gen_lr: 0.001
gen_betas:
  - 0.1
  - 0.99
disc_lr: 0.001
disc_betas:
  - 0.0
  - 0.999
ema_beta: 0.995

