# Experiment
experiment_name: stylegan-mnist

# Data
dataloader: MNISTDataloader

# Model
channels: 1
image_size: 32
latent_size: 64
n_mapping: 4

# Training
batch_size:
  4: 128
  8: 128
  16: 128
  32: 64
n_evals: 10
train_imgs: 21250000
warm_start: False
gen_lr: 0.001
gen_betas:
  - 0.1
  - 0.99
disc_lr: 0.001
disc_betas:
  - 0.0
  - 0.999
ema_beta: 0.995

