# Experiment
experiment_name: wgan-spotify


# Data
dataloader: SpotifyDataloader
meta_data_path: data/album_data_frame.json

# Model
channels: 3
image_size: 64
latent_size: 128

# Training
batch_size: 64
train_steps: 200000
eval_rate: 1666
warm_start: False
gen_lr: 0.0002
gen_betas:
  - 0.5
  - 0.999
disc_lr: 0.0002
disc_betas:
  - 0.5
  - 0.999
n_critic: 5
test_meta_data_path: data/test_data_meta.json
