# Experiment
experiment_name: wgan-mnist
unique_experiment_name: wgan-mnist_molto-deposition

# Data
dataloader: MNISTDataloader

# Model
channels: 1
image_size: 32
latent_size: 64

# Training
batch_size: 64
train_steps: 200000
eval_rate: 1666
warm_start: False
gen_lr: 0.0002
gen_betas:
  - 0.5
  - 0.999
disc_lr: 0.0002
disc_betas:
  - 0.5
  - 0.999
